ALTER TABLE 악보
    DROP PRIMARY KEY CASCADE;
ALTER TABLE 악보장르
    DROP PRIMARY KEY CASCADE;
ALTER TABLE 음반참여자
    DROP PRIMARY KEY CASCADE;
ALTER TABLE 악기
    DROP PRIMARY KEY CASCADE;
ALTER TABLE 판매자
    DROP PRIMARY KEY CASCADE;
ALTER TABLE 회원
    DROP PRIMARY KEY CASCADE;
ALTER TABLE 회원관심장르
    DROP PRIMARY KEY CASCADE;
ALTER TABLE 구매하다
    DROP PRIMARY KEY CASCADE;
ALTER TABLE 평점을매기다
    DROP PRIMARY KEY CASCADE;
ALTER TABLE 판매하다
    DROP PRIMARY KEY CASCADE;
ALTER TABLE 참여하다
    DROP PRIMARY KEY CASCADE;
ALTER TABLE 검색하다
    DROP PRIMARY KEY CASCADE;


DROP TABLE 악보장르;
DROP TABLE 음반참여자;
DROP TABLE 악기;
DROP TABLE 회원관심장르;
DROP TABLE 구매하다;
DROP TABLE 평점을매기다;
DROP TABLE 판매하다;
DROP TABLE 참여하다;
DROP TABLE 검색하다;
DROP TABLE 회원;
DROP TABLE 판매자;
DROP TABLE 악보;